name: Air Creative
favicon: null
layout_spectrum: 0.26454
typography_spectrum: 0.94765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#171717'
    - '#5e5e5e'
    - '#b6b6b6'
    - '#8f8f8f'
  brandStrength: 0.5132274385541677
  lightness: 0.1555847532581538
  saturation: 0.03110399004071951
  rhythmicContrast: 0.28639589808881283
purpose: []
